import 'dart:convert';

import 'package:covid_tracker/Model/world_states.dart';
import 'package:covid_tracker/services/utilites/app_url.dart';
import 'package:http/http.dart' as http;

class FetchWorldStates {
  Future<Autogenerated> getworldstates() async {
    final response = await http.get(Uri.parse(AppUrl.worldStatesApi));
    if (response.statusCode == 200) {
      var data = jsonDecode(response.body);
      return Autogenerated.fromJson(data);
    } else {
      throw Exception('error');
    }
  }
}

class FetchCountry {
  Future<List<dynamic>> getcountry() async {
    final response = await http.get(Uri.parse(AppUrl.countriesList));
    if (response.statusCode == 200) {
      var data = jsonDecode(response.body);
      return data;
    } else {
      throw Exception('error');
    }
  }
}
